### ISSUE TITLE
certain POST methods fail

### ISSUE THREAD

**Issue by arlogilbert** [J7mbo/twitter-api-php#99]
It appears that certain post methods succeed and certain methods fail.

For example lists/destroy fails - despite setting the list_id (and the other possible options) Twitter never sees the list_id

I'm guessing this is related to the issue that was closed (without resolution) by the other guy.

**Comment by phpfalcon** [comment]
same here

**Comment by arlogilbert** [comment]
@phpfalcon for what it's worth I found the codebird library works perfectly for all twitter api methods and took me about 5 minutes to replace this Twitter library. https://github.com/jublonet/codebird-php

**Comment by J7mbo** [comment]
Doesn't really help the community just suggesting a switch. We need to get to the root of this. PRs that prove it is fixed are welcome.

**Comment by nouchka** [comment]
Hello,
got the same issue: works well with statuses/update.json but fail with lists/members/create_all.json

didn't solve the issue but maybe it will help:
I added CURLOPT_VERBOSE and CURLOPT_STDERR in the performRequest. I tried to compare between curl command line working and libcurl from performRequest failing.
The Content-Type was different: multipart/form-data in performRequest as post values are passed in an array. So I tried to pass my post parameters in a string format (ex: list_id=198390090&screen_name=al_rousset)
Then I had an other error "Could not authenticate you", so I used the OAuth Tool from twitter to generate the authenticate header and then it works...
Then I tried a different parameter with a coma: list_id=198390090&screen_name=alainchretien,alain_gest and then I got the "Could not authenticate you". So I'm quite lost now...

**Comment by bobbrown** [comment]
I stopped in to say the same thing. I've not been able to do any list add or remove from lists.

**Comment by ashleydw** [comment]
+1 for me, I was trying to upload media through #91, and after fixing the headers, the parameters never get sent (update status ignore `trim_user` and `media_ids`).

I switched to codebird, thanks @arlogilbert

**Comment by J7mbo** [comment]
Media upload now fixed.

**Comment by testgonzo** [comment]
This API interface does not enable calls to twitter list related endpoints. I independently tried everything @nouchka described to no avail.  Surprised no one has figured this out in six years....

https://github.com/J7mbo/twitter-api-php/issues/99#issuecomment-78394687
